SELECT  A.EMPLID AS STUDENT_ID, 
        B.NAME AS NAME, 
        A.IMMUNIZATION AS IMMUN_CODE, 
        C.DESCR AS IMMUN_DESCRIPTION, 
        TO_CHAR(A.DATE_RECEIVED,'DD-MON-YYYY') AS DATE_RECEIVED, 
        TO_CHAR(A.DATE_TAKEN,'DD-MON-YYYY') AS DATE_TAKEN, 
        A.STATUS_IMMUN AS IMMUN_STATUS, 
        TO_CHAR(A.EXPIRATION_DT,'DD-MON-YYYY') AS EXPIRATION_DT
  FROM PS_IMMUNIZATIONS A, PS_PERSON_NAME B, PS_IMMUNIZATN_TBL C
  WHERE A.IMMUNIZATION IN ('01', '21', '32', '24', '25', '26')
     AND A.STATUS_IMMUN NOT IN ('M', 'E', 'N') 
     AND (A.EXPIRATION_DT >= SYSDATE OR A.EXPIRATION_DT IS NULL)
     AND A.EMPLID = (SELECT DISTINCT S.EMPLID 
                     FROM PS_STDNT_ENRL S 
                     WHERE A.EMPLID = S.EMPLID 
                     AND S.STRM >= '2111' 
                     AND S.STDNT_ENRL_STATUS = 'E' 
                     AND S.ENRL_STATUS_REASON = 'ENRL')
     AND A.EMPLID = B.EMPLID 
     AND A.IMMUNIZATION = C.IMMUNIZATION 
     AND C.EFFDT = 
        (SELECT MAX(C_ED.EFFDT) 
        FROM PS_IMMUNIZATN_TBL C_ED 
        WHERE C.IMMUNIZATION = C_ED.IMMUNIZATION 
          AND C_ED.EFFDT <= SYSDATE) 
ORDER BY A.EMPLID, A.IMMUNIZATION;
