SELECT * FROM PS_SCC_NTFREQ_HDR ORDER BY SCC_NTFREQ_ID DESC;
SELECT * FROM PS_SCC_NTFREQ_DTL ORDER BY SCC_NTFREQ_ID DESC;

SELECT * FROM PS_SCC_NTF_DTL_ER ORDER BY SCC_NTFREQ_ID DESC;

SELECT * FROM PS_SCC_NTFREQ_ITM ORDER BY SCC_NTFREQ_ID DESC;
SELECT * FROM PS_SCC_NTFREQ_RECP ORDER BY SCC_NTFREQ_ID DESC;
SELECT * FROM PS_SCC_NTFREQ_DATA ORDER BY SCC_NTFREQ_ID DESC;
SELECT * FROM PS_SCC_NTFREQ_RMDR ORDER BY SCC_NTFREQ_ID DESC;

SELECT * FROM PS_SCC_NTF_LOG ORDER BY SCC_NTFREQ_ID DESC;
SELECT * FROM PS_SCC_NTF_LOGPARM ORDER BY SCC_NTFREQ_ID DESC;

SELECT * FROM PS_ASU_AA_NFMS_TBL WHERE MILESTONE = 'GRBLK30PET';
SELECT * FROM PS_ASU_AA_NFML_TBL;
SELECT * FROM PS_ASU_AA_NFLN_TBL WHERE MILESTONE = 'GRBLK30PET' ORDER BY MILESTONE, MILESTONE_LEVEL, SEQUENCE_NBR;

SELECT * FROM PS_SCC_NTF_ADMN_VW;
SELECT * FROM PS_SCC_NTF_INSCNVW;

SELECT *
  FROM PS_SCC_NTF_INSTCON A
  , PS_SCC_NTF_CON_CFG B 
 WHERE A.SCC_NTF_CON_ID = B.SCC_NTF_CON_ID;
